### ISSUE TITLE
Ability to specify special characters to include/exclude

### ISSUE THREAD

**Issue by key10** [buttercup/buttercup-generator#4]
Many sites/apps specify which special characters/symbols can be used in creating the password. Currently the desktop app, and this generator, only allow a toggle of `symbols` or `!symbols`, which looks to be using the RegExp for all symbols. 

It would be good to be able to specify a sub-set of the special characters to use in password generation, so a user can select those that a given site/app allows. For flexibility, it would be nice to also allow specific symbols to be excluded. 

I can start looking at a way to implement this for a PR, but wanted to create the issue for tracking and feedback, and to get the idea out there in case others can get to it quicker than myself.

**Comment by sallar** [comment]
Thanks @key10 thats a great idea. Please consider [this PR](https://github.com/buttercup/buttercup-generator/pull/3) before doing any work. This will get merged by tomorrow.

**Comment by luislobo** [comment]
Just for reference, LastPass has this password generator https://lastpass.com/generatepassword.php

Copying a screenshot for posterity in case that service becomes unavailable.
![2017-10-31-10-28-36-screenshot](https://user-images.githubusercontent.com/453120/32232577-58c54e98-be26-11e7-96a6-b81d185aee41.png)

**Comment by perry-mitchell** [comment]
Thanks guys. Let’s continue this in #5
